### ISSUE TITLE
Interface Improvement -- "Publications: New Transcription XML"

### ISSUE THREAD

**Issue by caesarfeta** [perseids-project/perseids_docs#136]
Problematic user interface?  Short term fix should be documentation.  Long term fix should be an improved interface.  Before action can be taken we need to identify the most problematic views.  So let's start identifying them and assigning importance to fixing them.  Here's the basic reporting formula.

url:  http://sosol.perseids.org/sosol/publications/{n}
view: app/views/publications/show.haml
importance ( 1 to 5 ): 5
problem: Users have a hard time finding the very important/popular "New Transcription XML" link.  It should be made more prominent.

**Comment by balmas** [comment]
addressed with redesign
