### ISSUE TITLE
Perseids users receiving unwanted admin email

### ISSUE THREAD

**Issue by lcerrato** [perseids-project/perseids_docs#180]
A user reports that she is still receiving error messages and updates from admin@perseids.org. She was a student (in a summer course) and she's continuing to receive emails. 
I would suggest an unsubscribe option for users to opt out of notices. I didn't see this in the Perseids profile/user settings.
(I do not know if is this class/course specific or not).
Contact me for specific info on this case.

**Comment by balmas** [comment]
Resolved via #286
