### ISSUE TITLE
Deleting and editing comments before submission of alignments

### ISSUE THREAD

**Issue by nevenjovanovic** [perseids-project/perseids_docs#198]
In Perseids there is no option to delete unwanted comments before submitting alignments for review. When people, especially learners, submit text alignments, they sometimes need to delete their own comments (before submission) because they made a mistake; sometimes they push entire comment by mistake. 
Also, sometimes they remember something later, and would like to edit the existing comment. 

Ideally, making comments similar to what github has for issues and pull requests would be great.

**Comment by balmas** [comment]
to fix this we need to:

- [ ] add a link near the submit box for the user to access all the comments for the publication
- [ ] add an edit link for any comments they created on the item
- [ ] add a delete link for any comments they created on the item
- [ ] prevent users from deleting comments on the item that they didn't make
- [ ] prevent users from editing comments on the item that they didn't make
- [ ] prevent users from removing submit and and vote comments as these are important for the workflow
