### ISSUE TITLE
Vortex Workflow

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#234]
@Marie-ClaireBeaulieu would like the participants of the vortex workshop to be able to identify thematic relationships between texts and images as annotations, and then to be able to visualize the aggregation and frequency of the themes across the text and images.   Participants will also produce translation alignments of their texts.

Core requirements are 
1. the thematic relationships should be expressed with keywords (list still TBD) 
2. the annotation interface must be very easy to use and not intimidating to non-technical users
3. the participants should be able to see a visualization of the data at the workshop
4. the data produced at the workshop should be reusable

Additionally nice to have would be:
1. incorporation of the translation alignments into the visualization, following the model of the [Alpheios Enhanced](http://alpheios.net/content/aligned-translations) Text display, which enables mouseover highlighting of the aligned words.

**Comment by balmas** [comment]
Due to the limited time for implementation we will restrict the scope as follows:

1. We will limit the texts used for the workshop to texts that are available on Perseus already, and ideally already among the list of CTS-compliant texts. (Non-CTS compatibility is not necessarily a show-stopper, but this will depend upon the text and how hard it is to make it compatible).
2. All images used must be already available on the web under CC or able to be published under CC
3. Texts and images to be used should be identified before the workshop
4. We will use a temporary ontology for the thematic relationships, with the understand that the data should be mapped to a standard ontology, if an appropriate one exists, at some point in the future
5. The annotation workflow should use existing tools and workflows already supported on Perseids, with only modifications for supporting ontology
6. We will build a custom, stand-alone visualization of the annotations and alignments for purposes of use doing the workshop

**Comment by balmas** [comment]
Tools:

1. We will use Hypothes.is to annotate the texts 
2.  The images will be annotated using IMGSPECT
3. The translation alignments will be made using Perseids + Alpheios

**Comment by balmas** [comment]
Textual Data Format for Visualization:

1. We will use a modified version of the tools from the [tei-digital-age repo](https://github.com/PerseusDL/tei-digital-age) to merge the translation alignments and treebank data for each text into a single TEI XML file.

Each annotated word will be in a `<w/>` tag, and the thematic relationship keyword will be supplied in the @ana attribute and the translation alignment link in the @corresp attribute.

E.g.

`<w n="1-1"  corresp="tlg1396.tlg001.teida-eng1.xml#xpointer(//*[@n='1-1']) tlg1396.tlg001.teida-eng1.xml#xpointer(//*[@n='1-2'])" ana="keyword">ἐρρέτω</w>`

In this example, the `<w>` tag shown is from the source text, the value of the @corresp attribute points into the xml file containing the english translation and the value of the @ana attribute points into the treebank xml file containing the thematic keyword.

**Comment by balmas** [comment]
Image Data format for Visualization:

I'm not sure what the state and options are for the IMSPECT annotations at this stage or the best way to incorporate the data coming from it into the text annotations for visualization.  I will leave this up to @caesarfeta to figure out.  

In the ideal scenario, the annotations from IMSPECT would adhere to the Open Annotation data model, using the CITE urn of the image ROI as the target, and the keyword as the body, represented as an oa:Tag.  See http://www.openannotation.org/spec/core/core.html#Tagging

**Comment by balmas** [comment]
Prior to the workflow we will:

1) Ensure that all target texts are available for treebanking/translation alignment via the selectors in the corresponding Perseids input forms
2) Upload all images to a new vortex image collection in Imgcollect

The workflow at the workshop will be something like the following:

Annotation workflow:
1) login to Perseids
2) create new Treebank Annotation
3) annotate thematic relationships
4) create new Translation Alignment
5) align translation
6) submit treebank and translation alignment to Vortex Board
7) go to imgcollect and create the ROI annotations 
8) export ROI annotations for use in visualization (method TBD by @caesarfeta )

Creation of Dissemination (will require manual intervention and be done by Bridget)
1) export treebank and alignment data from board
2) create merged files using the modified xquery from the tei-digital-age
3) run TBD process to create visualizations 
4) deploy visualizations on Perseids server

**Comment by balmas** [comment]
The requirements for the Visualization process:

1. Ingest the TEI data (which will have translation alignment and thematic relationships identified in attributes on the w tags as described in prior comments)
2. Ingest the imgspect annotations
3. produce HTML5 display which shows frequency of thematic terms in a bar graph, the aligned translations in mouseover highlights, and images.  Exact functionality and details of what the display looks like to be worked out between @Marie-ClaireBeaulieu and @caesarfeta 
4. Requirements for deployment are that there is a single process which can be run to produce the visualization for any given set of text and annotations, and that the results can be deployed to an Apache webserver for dissemination

**Comment by ana** [comment]
Hi folks, @ana is not an attribute, it's an github user who has started to get automatically your comments on this issue.

**Comment by balmas** [comment]
Assignment of work:

1. @balmas will modify the tei-digital-age code to produce the merged TEI file
2. @Marie-ClaireBeaulieu will define the tagset for relationships
3. @balmas will produce and deploy the custom Arethusa configuration
4. @caesarfeta will make whatever changes are necessary to IMGSPECT to produce the ROI image annotations

**Comment by balmas** [comment]
whoops sorry @ana !! will fix

**Comment by ana** [comment]
Thanks @balmas :)

**Comment by balmas** [comment]
@caesarfeta I have put a sample of what the TEI XML with the merged alignments and relation tags will look like into https://github.com/PerseusDL/vortex_viz/tree/master/data/sample

It's up to you to figure out the best way to use this for your visualization. You're welcome to take a look at the code we original used for this in the [tei-digital-age](https://github.com/PerseusDL/tei-digital-age) demo, but the transformation to HTML is a little broken right now, because it uses out of date XSLT transformations.  It was pretty simple - the XML to HTML transform merged the aligned translation into the same HTML file as the source text, and the `@n` attributes became data attributes on span tags in the html. The javascript then operated on them.   If you want me to give you a full working sample of that HTML output for the translation alignments let me know and I'll pull it together. I just don't want to put the work in if you aren't going to use it.

**Comment by caesarfeta** [comment]
@balmas Message received.  I will contact you if I run into insurmountable problems.

**Comment by balmas** [comment]
NB, the code and documentation for this workflow is now in its own repo at https://github.com/perseids-project/thematic-annotation-prototype
