### ISSUE TITLE
English treebanking tag set

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#237]
@gcelano requests that we create a treebanking tagset for english from 

https://github.com/gcelano/Stanford_Dependencies/blob/master/morph_tagset.json
and

https://github.com/gcelano/Stanford_Dependencies/blob/master/syn_tagset.json

**Comment by balmas** [comment]
@gcelano I have these in the arethusa-configs now as arethusa.morph/english.json and arethusa.relation/english.json but there is more work needed on the morph tag set in particular -- we need the posttag mappings, etc.

https://github.com/latin-language-toolkit/arethusa-configs/blob/english/configs/arethusa.morph/english.json
https://github.com/latin-language-toolkit/arethusa-configs/blob/english/configs/arethusa.relation/english.json

do you want to take a stab at that?

**Comment by gcelano** [comment]
Hi Bridget,

What should I need to make it possible to use the English tagset?

Giuseppe

2015-04-02 15:32 GMT+02:00 Bridget Almas <notifications@github.com>:

> @gcelano <https://github.com/gcelano> I have these in the
> arethusa-configs now as arethusa.morph/english.json and
> arethusa.relation/english.json but there is more work needed on the morph
> tag set in particular -- we need the posttag mappings, etc.
>
>
> https://github.com/latin-language-toolkit/arethusa-configs/blob/english/configs/arethusa.morph/english.json
>
> https://github.com/latin-language-toolkit/arethusa-configs/blob/english/configs/arethusa.relation/english.json
>
> do you want to take a stab at that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerseusDL/perseids_docs/issues/237#issuecomment-88898144>
> .
>



-- 
Dr. Giuseppe G. A. Celano
Postdoctoral Researcher
Universität Leipzig
Institute of Computer Science,
​Section of ​
Digital
​ ​
Humanities
​

Augustusplatz 10
04109 Leipzig
​ (DE)​

E-mail: giuseppegacelano@gmail.com
            giuseppe.celano@tufts.edu
            celano@informatik.uni-leipzig.de
Web site 1: http://www.dh.uni-leipzig.de/wo/team/
Web site 2: https://sites.google.com/site/giuseppegacelano/

**Comment by balmas** [comment]
Hi Giuseppe, the morph tag set needs to be formatted like the others, e.g. https://github.com/latin-language-toolkit/arethusa-configs/blob/master/configs/arethusa.morph/lat_attributes.json ... the postag schema, etc.

**Comment by gcelano** [comment]
hi Bridget,

is this what you need?

https://github.com/latin-language-toolkit/arethusa-configs/blob/gcelano/configs/arethusa.morph/english.json

2015-04-07 13:30 GMT+02:00 Bridget Almas <notifications@github.com>:

> Hi Giuseppe, the morph tag set needs to be formatted like the others, e.g.
> https://github.com/latin-language-toolkit/arethusa-configs/blob/master/configs/arethusa.morph/lat_attributes.json
> ... the postag schema, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerseusDL/perseids_docs/issues/237#issuecomment-90514208>
> .
>



-- 
Dr. Giuseppe G. A. Celano
Postdoctoral Researcher
Universität Leipzig
Institute of Computer Science,
​Section of ​
Digital
​ ​
Humanities
​

Augustusplatz 10
04109 Leipzig
​ (DE)​

E-mail: giuseppegacelano@gmail.com
            giuseppe.celano@tufts.edu
            celano@informatik.uni-leipzig.de
Web site 1: http://www.dh.uni-leipzig.de/wo/team/
Web site 2: https://sites.google.com/site/giuseppegacelano/

**Comment by balmas** [comment]
Hi Giuseppe, no, you need to do the following:

1) identify the field order for the postag
e.g. 
` "postagSchema" : [
    "pos",
    "pers",
    "num",
    "tense",
    "mood",
    "voice",
    "gend",
    "case",
    "degree"
  ],`

says that the the postag is made up of the following fields in this order:
pos, pers, num, tense, etc.

And then for each of these fields you need to define the way they are displayed and encoded.

E.g. 
`"attributes" : {
    "pos" : {
      "long" : "Part of Speech",
      "short" : "pos",
      "values" : {
        "noun" : {
          "long" : "noun",
          "short" : "noun",
          "postag" : "n",
          "style" : {
            "color" : "rgb(43, 114, 124)"
          }
        },`

says that the descriptive label for the field identified as 'pos' is 'Part of Speech', that the key  for it is 'pos', and that one possible value for it is 'noun', and the long description of this value is 'noun', as is the key for it, that when it's stored in the postag field it's stored as 'n' and and that when it's selected for a form that form gets styled with the color red.

**Comment by gcelano** [comment]
Do I have to use "attribute" even if there are no "values" (i.e., the
labels are considered as non-composite) and I can just add "short name",
"long name", and "color"? Thanks

2015-04-08 15:49 GMT+02:00 Bridget Almas <notifications@github.com>:

> Hi Giuseppe, no, you need to do the following:
>
> 1) identify the field order for the postag
> e.g.
> "postagSchema" : [
> "pos",
> "pers",
> "num",
> "tense",
> "mood",
> "voice",
> "gend",
> "case",
> "degree"
> ],
>
> says that the the postag is made up of the following fields in this order:
> pos, pers, num, tense, etc.
>
> And then for each of these fields you need to define the way they are
> displayed and encoded.
>
> E.g.
> "attributes" : {
> "pos" : {
> "long" : "Part of Speech",
> "short" : "pos",
> "values" : {
> "noun" : {
> "long" : "noun",
> "short" : "noun",
> "postag" : "n",
> "style" : {
> "color" : "rgb(43, 114, 124)"
> }
> },
>
> says that the descriptive label for the field identified as 'pos' is 'Part
> of Speech', that the key for it is 'pos', and that one possible value for
> it is 'noun', and the long description of this value is 'noun', as is the
> key for it, that when it's stored in the postag field it's stored as 'n'
> and and that when it's selected for a form that form gets styled with the
> color red.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerseusDL/perseids_docs/issues/237#issuecomment-90922505>
> .
>



-- 
Dr. Giuseppe G. A. Celano
Postdoctoral Researcher
Universität Leipzig
Institute of Computer Science,
​Section of ​
Digital
​ ​
Humanities
​

Augustusplatz 10
04109 Leipzig
​ (DE)​

E-mail: giuseppegacelano@gmail.com
            giuseppe.celano@tufts.edu
            celano@informatik.uni-leipzig.de
Web site 1: http://www.dh.uni-leipzig.de/wo/team/
Web site 2: https://sites.google.com/site/giuseppegacelano/
