### ISSUE TITLE
Load texts for Vortex workshop

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#239]
We need the following texts loaded in the annotsrc inventory:

- [x] Aristophanes Clouds English tlg0019.tlg003.perseus-eng1
(needs milestones converted to divs)

- [x] Plato Ion tlg0059.tlg027.perseus-grc1 and tlg0059.tlg027.perseus-eng1 
(needs milestones converted to divs)

- [x] Hesiod, Theogony

- [x] Euripides, Heracles

- [x] Aristophanes, Birds (need English loaded)

- [ ] Apollonius Rhodius, Argonautica, 

- [ ] Lucian, De sacrificiis

- [ ] Lucian  Prometheus

- [ ] Plato Euthydemus tlg0059.tlg0021.perseus.grc1 & tlg0059.tlg021.perseus-eng1
(needs milestones converted to divs)
 
- [ ] Nonnos tlg2045.tlg001.perseus-grc1

- [ ] Dio Chrys Oratio tlg0612.tlg001-perseus-grc1

- [ ] Euripides Helen tlg0006.tlg014.perseus-grc1 & tlg0006.tlg014.perseus-eng1 (english is under copyright)

- [ ] Homeric Hymn Apollo

- [ ] Euripides, Ion

- [ ] Callimachus, Hymn Delos, 307-321

- [ ] Plutarch, Theseus

- [ ] Aeschylus, Eumenides

- [ ] Diodorus

- [ ] Euripides, Bacchae

- [ ] Aristophanes, Wasps

- [ ] Aristophanes, Peace

- [ ] Plato, Phaedo (Need English)

**Comment by srdee** [comment]
@balmas I'll try to do as many of these as possible tomorrow (Tuesday 4/14/15), and check them off accordingly

**Comment by balmas** [comment]
@srdee that's awesome - we don't need them all  in time for the workshop (because there is no way they will be able to do that much annotation there), I just need to make sure at least one to two of everyone's preferred texts are available. The top priority still outstanding in this list to make sure that is the case is Hesiod Theogeny.

**Comment by srdee** [comment]
@balmas roger that!

**Comment by srdee** [comment]
Some of these are also now in French: https://github.com/OpenGreekAndLatin/french_trans-dev

...should I clean up some of those, too? What's our workflow for incorporating OPP texts?

(no need to answer until post-Vortex)

**Comment by Marie-ClaireBeaulieu** [comment]
Thanks Stella! Yes, I think it would be great to have those CTS-ized for the continuation of the project!

MC

Marie-Claire Beaulieu
Assistant Professor
Department of Classics
Tufts University
________________________________

**Comment by balmas** [comment]
Entry point to instructions for adding a text for annotation: https://github.com/PerseusDL/tei-conversion-tools/wiki/Scholar-or-Student-Wanting-to-Make-Text-Ready-for-Annotation
