### ISSUE TITLE
Problem with Treebank Editor and XML

### ISSUE THREAD

**Issue by TDBuck** [perseids-project/perseids_docs#280]
I was booted from my treebanking session after about an hour in. When I logged back in all the lemma and form data was random strings of characters. The actual XML editor is also really slow, making it difficult to pull an example. 

![treebug](https://cloud.githubusercontent.com/assets/13625384/9204726/7a510b80-402c-11e5-8bd1-04b858109f44.png)

**Comment by balmas** [comment]
Oh dear that's frightening. Will take a look. I think there is definitely something going wrong with the XML editor too. Will look at both.

**Comment by TDBuck** [comment]
Closed it out and opened it again and this time everything was back to normal. Even all the changes I made up to the point when it wouldn't let me save worked. So I have no clue what happened. But it is certainly a bug.

**Comment by balmas** [comment]
The bad strings are probably just caused by a misconfigured Unicode setting

**Comment by balmas** [comment]
can you send me a link to the file you were testing with?

**Comment by TDBuck** [comment]
this is the most recent version. everything seems back to normal.

I noticed that the XML editor only seemed to get bogged down with large
files, so I figured this treebank would be a good test.

**Comment by balmas** [comment]
yes there is definitely a problem with the large xml files that I need to investigate. But something is also wrong with the handling of the unicode on the saves too.

**Comment by balmas** [comment]
@TDBuck okay, performance on editing XML of treebank files and translations should be improved. Please test and confirm.

Also , the unicode encoding errors should now also be fixed. Please test creating treebank files with Greek chars, saving from Arethusa and confirm that all unicode is properly preserved.

**Comment by TDBuck** [comment]
everything looks good and back to normal.
