### ISSUE TITLE
issue for Lane's Arabic-English lexicon display

### ISSUE THREAD

**Issue by lcerrato** [perseids-project/perseids_docs#317]
As this is a GitHub orphan at the moment, per the instructions https://github.com/PerseusDL/tei-conversion-tools/wiki/Questions-and-Decisions,-Asking-and-Reaching:

Dear Sir,
The colors used in words of different languages in Lane's Dictionary are not very distinct. There should be an option to change the color.

Best regards,
Mazhar

**Comment by balmas** [comment]
this is not a perseids issue so closing - has been recorded in the correct rep at https://github.com/PerseusDL/Perseus5/issues/29
