### ISSUE TITLE
Visualization for Tufts Myth 2015 annotations

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#329]
This item will track the requirements for the visualization of the annotations created by Tufts Myth 2015

**Comment by balmas** [comment]
If we want to display the texts of citations referenced as attestations and characterizations, these all need to be through the P4 to P5 conversion process

**Comment by balmas** [comment]
We need to decide if we want to use the JOTH/GapVis display, or something new, e.g. based on Nemo and Arethusa

If we have no place annotations, I'm not sure GapVis makes sense here

**Comment by balmas** [comment]
What we were previously referring to as attestations should not be identified instead as characterizations

**Comment by balmas** [comment]
And what we now have as attestations are attestations to the relationships, so should be linked in some way to the social network graph

**Comment by balmas** [comment]
Note also, for attestations, it seems, at least for the set I'm looking at for Selene, the name of the person in the relationship was highlighted, rather than the words describing the relationship. We had actually intended for the latter to be what was selected as the target, since the attestation is to the relationship not the names person.

**Comment by balmas** [comment]
adding @Marie-ClaireBeaulieu to the participants on this item

**Comment by balmas** [comment]
At least some annotations have the relationships done in the wrong order. 

The instructions said that they should have made sure the subject of the Smith's entry was the subject of the relationship statement. But e.g.  https://hypothes.is/a/NL0iDrXsRNOrLWUa6ejV-g has this done the other way around, so that this annotation effectively says:

Selene is the Brother of Phoebus

**Comment by Marie-ClaireBeaulieu** [comment]
Yes, we've had trouble with this because one of the TAs went around saying the wrong thing, and it took some time until I was made aware of this.

**Comment by balmas** [comment]
JOTH GapVis modifications can be found in https://github.com/perseids-project/gapvis/pull/7

We probably won't make further enhancements to this display code.  Ideally this should move into Nemo and/or Arethusa. We may also use this as a test case for BSP visualization service integration.

See also related item https://github.com/Capitains/CTS5-XQ/issues/32 which is causing some of the attested/characterization texts which have been converted to not display. That will be fixed there, or if we can't then we might want to update the annotations to use "valid" passage ranges.

**Comment by balmas** [comment]
See also #330 which lists approved annotations which had errors and couldn't be converted.

**Comment by balmas** [comment]
@Marie-ClaireBeaulieu I have finalized and converted all of the annotations approved so far from the myth 2015 class.  These are deployed, along with the original joth annotations, in the staging environment at http://www.perseids.org/sites/myth/#index

I think for next steps, we need a few things from you:

- [ ] Review the displays of the new characters and make sure nothing seems amiss to you (other than the errors already pointed out above)
- [ ] if we want to keep this as a combined display, and have it replace the current JOTH display, then we probably need to make some some changes to the site title and explanatory text.  Can you review that and let me know what you want to do? The staging environment has the title "Myth 2015" rather than "Journey of the Hero" but the text is all the text from the original publication.
- [ ] approve the remaining publications (after which I will finalize and convert them)
- [ ] decide if you want to go in and fix and resubmit any of the annotations which were producing errors
- [ ] decide if you want to review and fix the relationships which are pointing the wrong way

**Comment by balmas** [comment]
Also, note that I took a different approach to finalization to save time.  I downloaded all of the approved publications and did a batch conversion offline, rather than to follow the laborious step of clicking on the create link for each annotation in the preview display.  (I think that prototype feature is one we can probably retire now).  When I finalized, as this is an end-user community, the original annotations are all now in your user account on Perseids.  I don't think you really need to commit any of those to perseids master if you don't want, because they are just the temporary annotations containing the ingested hypothes.is links and as such aren't really worth much.  I'd say you could just delete them from your account.  For future class work we should consider whether the new master community board is a better approach -- this one goes direct to master and doesn't require the end-user loop.

**Comment by Marie-ClaireBeaulieu** [comment]
@balmas : OK, thanks. I reviewed the display and it looks fine, except of course for the known issues. I will produce new introductory text when we have a better sense of the overall direction we want to take with this. I have now accepted or cleaned up the remaining submissions on the myth board, so this is all done for now.

**Comment by balmas** [comment]
Ok for the moment I have tweaked the title and text slightly to indicate that it is a work in progress.
