### ISSUE TITLE
New Myth Workflow-annotations to Smith's dictionary

### ISSUE THREAD

**Issue by Marie-ClaireBeaulieu** [perseids-project/perseids_docs#335]
Refer to issue #330 (errors in annotations) and #331 (texts that needed to be converted) #329  (visualization for myth annotations). 

2015 workflow described in detail <a href="https://github.com/perseids-project/perseids_docs/wiki/Hypothes.is-annotations-for-Classical-Mythology-2015"> here </a>

2014 workflow described in detail <a href="https://github.com/perseids-project/perseids_docs/wiki/hypothes.is-annotations"> here </a>

See also MC's fabulous practice website (made with the text from the wiki): http://marie-clairebeaulieu.github.io/Hypothes.is%20annotations/InstructionsHypothesis.html

**Comment by Marie-ClaireBeaulieu** [comment]
Notes from meeting on 1/19
-Gephi co-occurrence graphs
-Last session= integrate all results

-Have linked data as a thread

-co-occurrence overlap with social network

-Talk to Ryan Cordell about ordering lessons on network analysis

-what tasks the students would do?
-Define the technical skills learned: linked data models

-reflection on what they found through digital vs analog tools

-MCB to perform recall on chapter 3 of her own book: are analog results reproducible/better with digital workflow? What does each teach us?

-MCB to come up with list of tasks, FB to add digital tasks

-one of the tasks could be to correct old data: plausibility analysis
	-students check each other= peer review task

**Comment by Marie-ClaireBeaulieu** [comment]
Objective
-Design a set of digital assignments that will complement and enhance the students’ term project
-Continue to build up Smith’s dictionary as a resource
-Transmit digital skills/knowledge/awareness to the students

Common thread throughout assignments
-Techniques, concepts, and best practices related to working with linked data

Context
-We now have data produced by students and accumulated over 2 semesters. Some of this data contains errors, and the workflow was experimental. We are now looking to establish a workflow that mitigates the probability for errors, is more streamlined for the user, and teaches the students about the data they are producing (principles of putting data together as well as interpretation)
-After our conversation on 1/19, it seems like a good idea to design this workflow so that students could correct and enhance data produced in earlier iterations rather than annotate new entries.

**Comment by Marie-ClaireBeaulieu** [comment]
-Possible assignments for Sept. 2016:

<ul><li>Persons: no differentiation was made between (mortal) persons, deities, demi-gods. Perhaps an assignment that could refine this categorization would be a good place to start for the students to become familiar with the project. We currently have persons annotated, and this seems to have been done with a fair degree of accuracy.</li>

<li>Relationships: the direction of relationships has caused trouble and needs to be checked. A visualization or tree structure would be really helpful in identifying and fixing issues. We explored the treebanking functions in Arethusa for this, but without much success, as the treebanking makes it impossible to describe relationships other than direct dependency (e.g. sibling relationships, or the complicated relationship between Hera and Zeus). </li>

<li>Relationships 2 (+ attestations of relationships): at this stage, it would be helpful to start considering alternative versions of relationships in conjunction with the "attestation of relationship" annotations. E.g. in the Iliad, Poseidon is the father of Theseus, but in Herodotus, it's Aegeus, and Plutarch says it's both (I don't know if that's true, but this is for the sake of example). We currently have the attestations annotated, but need a way to represent the different alternative relationships and their attestations. Would a co-occurrence graph work for this?</li>

<li>Characterizations: By far the most successful exercise in 2015. Students used Anna Krohn's <a href="http://sites.tufts.edu/perseids/projects/breaking-the-language-barrier/"> Breaking the language Barrier </a> series of exercises on using Perseus to find Greek words that describe their assigned mythological figure and annotated the Smith entry with the Greek word and its English equivalent, while providing the Perseus stable ID for the quotation. It would be worth spending at least two class sessions on this. We need a way to visualize the Greek and English neatly while keeping the active link to the Perseus text.</li>

<li>A comprehensive exercise: at the end of the semester, students could produce a visualization of their work that encompasses all they did. Ideally, we would have a way to see their character's co-occurrence with other figures and students would be asked to provide an interpretation of the data. This interpretation could be integrated to their term paper. Concurrently, MCB would do the same series of exercises as the students on the figure of Danae (which is discussed in chapter 3 of her book) and show the results obtained. Different or similar to the analog method? What do we learn from each?</li></ul>

**Comment by Marie-ClaireBeaulieu** [comment]
@fbaumgardt : let me know if you have any questions!

**Comment by Marie-ClaireBeaulieu** [comment]
additional note: the students are organized in teams of 2 or 3. The exercises can be designed for teamwork, but could also be done individually so long as there is a way to integrate all team members' contributions to the entry in Smith.

**Comment by fbaumgardt** [comment]
Sorry, this fell through last week,al though I remembered you assigned me. This is a good start, and I’d suggest that from this we make a definite list of the annotations/vocabularies we want to provide once I have a basic set-up for linked-open-data annotations in Arethusa.
