### ISSUE TITLE
we need to define API terms of service

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#341]
as we move closer to having a published API for Perseids, we should really have a terms of service which is specific to its use by client applications.  These are different the end-user terms of service because they are directed to external clients who might make requests on behalf of users.  The first two users of this are going to be Attic Inscriptions Online and Syriaca.

@lcerrato would love to collaborate with you on this one if you're up for it!

**Comment by lcerrato** [comment]
Sure thing.

**Comment by lcerrato** [comment]
What kind of data is going to be passed back and forth and what are the expectations Perseids has of the external clients (and vice versa)?

**Comment by balmas** [comment]
Data: 
- any data type that is supported/managed on perseids (transcriptions, translations, annotations, gazetteers, ...)
- individual user data (no passwords, but may include any information they make available about their account, including email address)

The API uses OAUTH (http://oauth.net/2/) so the user has to explicitly grant the client application the rights to perform the requested action(s) . Currently, we have defined 2 scopes: read and write. We can make this more fine-grained as needed though.

I need to think a bit about expectations. Certainly that the protocols (such as oauth2) are adhered to.  But we probably need to say something about reasonable usage limits, etc.  

Here are some example terms of service we could look at for ideas:

https://developers.google.com/terms/
https://developers.google.com/youtube/terms?hl=en
https://dev.fitbit.com/terms

**Comment by lcerrato** [comment]
Note to self

https://slack.com/terms-of-service/api

**Comment by lcerrato** [comment]
As a side note, it may be time to consult with technology transfer about the legalese.

**Comment by balmas** [comment]
good idea. This is one of the things I was planning to bring up at the meeting with the GIS Portal guy next week...

**Comment by balmas** [comment]
I'm going to deploy our initial draft of this tonight. Even if we need to refine it still, it's better than what we have now.  The file that we should edit going forward is this one:

https://github.com/PerseusDL/perseids_private_config/blob/master/sosol/initializers/site.terms.erb
