### ISSUE TITLE
How does Validation work?

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#355]
@balmas Is it the case that we cannot submit a record if it does not validate?

I got this error:

Submit http://syriaca.org/place/1814 to Perseids

Submitting record...

Failed submission: 500 500 element "sourceDesc" not allowed yet; missing required element "seriesStmt"

**Comment by davidamichelson** [comment]
p.s. somehow the permissions on this issue list do not allow me to add a label for Syriaca. Could you enable that please so we can label our issues to find them again?

**Comment by balmas** [comment]
there is already a Syriaca label -- I've just added it to this issue. Can you not see it when you enter a new issue?

(I will respond to the validation question shortly)

**Comment by balmas** [comment]
ah re the labeling you may need to be a collaborator on the repo to label. I've just sent invites to you and @wsalesky . Let me know who else to add.

**Comment by balmas** [comment]
And yes, it's true that you cannot submit an invalid record.  Is this going to be a problem? I assumed you would want to enforce validation. I can relax that but then you may get invalid data submitted.

**Comment by wsalesky** [comment]
This may be a good time to update the scheme.

**Comment by balmas** [comment]
@wsalesky - do I have the latest one?

**Comment by wsalesky** [comment]
@balmas I think you do have the latest, we need to do some work to update our schema. This may delay testing though. @davidamichelson, @dlschwartz  what do you think?

**Comment by balmas** [comment]
We could also turn off the validation for purposes of the rest of testing, and then turn it back on again.

**Comment by wsalesky** [comment]
I would be in favor of that.

**Comment by balmas** [comment]
ok, shall we make an executive decision or wait for @davidamichelson and @dlschwartz to weigh in ? :)

**Comment by dlschwartz** [comment]
Sorry, just back from a meeting. Let's test without validation for the time
being.


On Tue, Sep 20, 2016 at 1:21 PM, Bridget Almas <notifications@github.com>
wrote:

> ok, shall we make an executive decision or wait for @davidamichelson
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_davidamichelson&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=axlKdK1vdS2d7ktYt4qSE6P4J6w5Lys6PhzmyzIrq6I&s=F9ADktZ1jcbHWTB1OOWBQoZ95dAcum6VL9O1n3K1z5E&e=>
> and @dlschwartz
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=axlKdK1vdS2d7ktYt4qSE6P4J6w5Lys6PhzmyzIrq6I&s=eL15vqGPCv5llwh2vPRmI9-n40pAZoGPbSYM2buBW3c&e=>
> to weigh in ? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_perseids-2Dproject_perseids-5Fdocs_issues_355-23issuecomment-2D248387495&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=axlKdK1vdS2d7ktYt4qSE6P4J6w5Lys6PhzmyzIrq6I&s=7esz6RR1CSRRZ7fQkzziahgcbYNa4yG0nH2HOCNpVAA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNztRdEI2lFTtZYe6X2e3DtIzhxER1ks5qsCQNgaJpZM4KB0Fn&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=axlKdK1vdS2d7ktYt4qSE6P4J6w5Lys6PhzmyzIrq6I&s=9O12mDcTsMhFVcTRCvGWvNoez65pyCNeDjQhWHaDrdI&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by davidamichelson** [comment]
Thanks as an FYI, when I post an issue it does not let me choose a tag.
Permission issue?

**Comment by balmas** [comment]
@davidamichelson I think you need to accept my request to become a collaborator on this repo, then you can assign labels to items.

**Comment by balmas** [comment]
Ok, I've disabled validation on the syriaca documents for the time being.  This means you could get complete junk of course, so I do think we should reenable it before people start using this, but it will make it easier for you to test the workflow in the meantime.
