### ISSUE TITLE
Need clearer labelling

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#360]
Would it be possible to use a bit more HTML styling to make the work flow and buttons clearer please?

For example:
From the overview of a record page: http://sosol.perseids.org/sosol/publications/26008, it is not clear that  XML Preview is two buttons rather than one.

Also, "View in Catalogue" is unclear as a label.

It would be nice either to customize these labels or to come up with a clear set of definitions please.

**Comment by davidamichelson** [comment]
Similarly this phrase: "Review Syriaca Place Gazetteer Board - http://syriaca.org/person/3027 from publication NathanGibson/person-3027" 
is confusing.

Found here: http://sosol.perseids.org/sosol/publications/26008/syriaca_identifiers/38146/editxml

**Comment by balmas** [comment]
These are good suggestions. I will look into this and provide some feedback on what is possible.

**Comment by balmas** [comment]
XML/Preview buttons now clearly differentiated.

Still to do:

[ ] view in catalog -  need advice on what this should say for Syriaca documents.
[ ] title for review screen - need advice on what this should say for Syriaca documents
