### ISSUE TITLE
Unused fields in Board Dashboard

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#361]
There are several custom columns in the board dashboard:

Passage Text    Transcription Text (EpiDoc)     Translation Text (EpiDoc)   Text Annotations    Commentary Annotation   Treebank Annotation     Alignment Annotation    Annotation  Annotation (JSON-LD) 

Not all of these are relevant to our project, we don't mind having them present but would it be possible to put the universally used columns to the left (first) if there are any? Or having custom views per board?

**Comment by balmas** [comment]
yes, cleaning this up is part of our planned new design.

**Comment by balmas** [comment]
addressed in new design.
