### ISSUE TITLE
How do we set the finalizer?

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#362]

**Comment by balmas** [comment]
It currently is assigned randomly, and then any member on the board can go ahead and reassign it to themselves, by clicking the title of the publication in the boards view.  I know you want the ability to assign specific reviewers and finalizers, and that is on the to-do list, but we said it would be after this first phase of integration with the existing functionality.

**Comment by balmas** [comment]
this is implemented and deployed now.
