### ISSUE TITLE
How do we set the number of approvers required?

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#363]

**Comment by dlschwartz** [comment]
This is asking a lot but could we allow up to three people to approve within a window of something like three weeks. However, provided at least one person has approved, it would automatically be sent to the finalizer at the end of that time frame.

**Comment by balmas** [comment]
hmm. that's a very interesting feature request. I will investigate and get back to you!

**Comment by balmas** [comment]
Instructions to manage the Syriaca Community and Board:

If you are a Community Admin (which right now Winona, Dave, Daniel, Jeanne-Nicole and Nathan all are), you will see the Communities button on the left side of your home screen.

![syrcom1](https://cloud.githubusercontent.com/assets/644870/22021546/f60b4856-dc8b-11e6-85e8-979a2de4533e.png)

Click that, and you will see at the top of the next screen, a Manage Community button:

![screenshot from 2017-01-17 08 05 07](https://cloud.githubusercontent.com/assets/644870/22021565/04e94e18-dc8c-11e6-87d5-be5470fffb79.png)

From there you can edit the community
![screenshot from 2017-01-17 08 08 14](https://cloud.githubusercontent.com/assets/644870/22021583/201cc89a-dc8c-11e6-813c-8a539a9883dd.png)

At the top, you can change the display ('friendly') name, the description, whether or not to allow self-signup, the URL for the final github repo, and the number of voters to whom you can assign items for voting.  Note voter assignment limits are not the same as decree limits.  You could have more voters assigned than are needed to approve or reject an item.

![screenshot from 2017-01-17 08 10 36](https://cloud.githubusercontent.com/assets/644870/22021659/72970c3e-dc8c-11e6-8348-f2337d8611c9.png)

Scroll down and you can edit the Board, members and admins of the community

![screenshot from 2017-01-17 08 10 12](https://cloud.githubusercontent.com/assets/644870/22021666/80af8dfa-dc8c-11e6-87f4-8f03146d32e5.png)

Click Edit on the Board to edit voting requirements and email templates
![screenshot from 2017-01-17 08 11 52](https://cloud.githubusercontent.com/assets/644870/22021695/a08a4b74-dc8c-11e6-8310-3b4dfd01dd8a.png)

'Members' are the list of Perseids Users who are allowed to vote on items.

'Decrees' is where you set which and how many votes are needed for approval or rejection. You can set this to absolute vote #s or a percentage of board membership.

'Emails' is where you set what emails are sent to whom when and what they say.
