### ISSUE TITLE
When we submit a record to perseids from our Syriaca.org local admin could it go directly to the board rather than to one's home?

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#365]
When we submit a record to perseids from our Syriaca.org local admin could it go directly to the board rather than to one's home?

Currently there are extra clicks because the upload from Syriaca.org does not go directly to a board. The user has to submit it in persieds. Could we skip this step if the user is already authenticated and our upload script knows which board?

**Comment by balmas** [comment]
The Perseids API does already support submission as a separate call, so this would be up to @wsalesky to answer :)

**Comment by wsalesky** [comment]
Yes, I can take a look at that. @balmas is this the same as the community_name?

**Comment by balmas** [comment]
@wsalesky see the instructions at http://perseids-project.github.io/integrations-cookbook/clients/#setting-the-review-community and then http://perseids-project.github.io/integrations-cookbook/clients/#submitting-to-the-review-community and let me know if that makes it clear. thanks!

**Comment by wsalesky** [comment]
@balmas I am submitting to: 
https://sosol.perseids.org/sosol/api/v1/publications/

Using the publication id returned by my initial submission. Although I get a 200 response I do not see the board being updated. Am I using the wrong id? In my initial POST to sosol I get an id and a publication number returned ex:
`{
"id":38905,
"type":"SyriacaIdentifier",
"publication":26768,
"publication_community_name":"PerseidsMaster",
 "content":"<?XML CONTENT ... 
}`

**Comment by balmas** [comment]
@wsalesky are you doing a POST to (e.g.)

https://sosol.perseids.org/sosol/api/v1/publications/26768/submit?comment=clientsuppliedsubmitcomment

(after doing the PUT to set the review community?)

**Comment by wsalesky** [comment]
Thanks, I was not doing the final POST. It is working now.
