### ISSUE TITLE
We find the "publication overview" page slightly confusing and redundant

### ISSUE THREAD

**Issue by davidamichelson** [perseids-project/perseids_docs#368]
http://sosol.perseids.org/sosol/publications/26227

This may just mean a need for different labelling.

**Comment by balmas** [comment]
agree. This is one of the screens set for redesign.  The current proposed design is here:

http://perseids-project.github.io/perseids-design/design/pubOverview.html

Feedback on if/how you would like to see the new design changed would be welcome!

**Comment by balmas** [comment]
See #374

**Comment by balmas** [comment]
Current implementation:

![overview](https://cloud.githubusercontent.com/assets/644870/20977771/8976e718-bc74-11e6-92af-66b4462343c5.png)
