### ISSUE TITLE
deploy syriaca schema from external repo

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#370]
We want to deploy the syriaca schema direct from their github repo, rather than keeping a copy of it on ours.  Requires adding this to the puppet config, and referencing it from a full path rather than local to sosol.

**Comment by balmas** [comment]
need to find out from @wsalesky if an RNG version of the schema can be created and kept in the srophe repo. If not, will find libraries for conversion and build into deployment process. (NB the python converter at http://www.gnosis.cx/download/relax/ doesn't like the schema. I have so far converted it manually using oXygen. Next step would be to check Trang. http://relaxng.org/#conversion)

**Comment by wsalesky** [comment]
We can do that. Here is the current version:
https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/documentation/syriaca-tei-main.rng
