### ISSUE TITLE
create pass_through community board for zagreb psl

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids_docs#373]
Request from @nevenjovanovic

Community and Board Name:  "Zagreb PSL"
Reviewers: Neven (nevenjovanovic-aai) and Alex Simrell (asimrell1)
Passthrough URL: https://github.com/nevenjovanovic/zagreb-psl

(PSL stands for "Prevodjenje s latinskog" (Latin Translation -- one of our undergraduate courses).

- [x] fork repo to perseids-proxy-user
- [x] create proxy
- [x] deploy configuration
- [x] create community and board
- [x] notify Neven it's ready

**Comment by balmas** [comment]
@TDBuck the configuration should be deployed by 9am today.  Please create the community and let Neven know when it's ready. Thanks!

**Comment by TDBuck** [comment]
All set up, let me know if there are any problems with the board/community

**Comment by balmas** [comment]
super. Thanks!
