### ISSUE TITLE
Adding log to Overview

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#392]
In the Overview area of a record (e.g., http://sosol.perseids.org/sosol/publications/26783), can we show the latest actions/comments as well as the username for each one? We'd like this area to show a clear sense of what's happening to the record.

**Comment by balmas** [comment]
deployed.  The fix shows the last 5 commits in the overview (next to the identifier title) and also adds a history button to the bottom of the page for retrieval of more.

@nathangibson let me know if this works for you.
