### ISSUE TITLE
Add ability to define/refine your available ontologies and subject ?

### ISSUE THREAD

**Issue by PonteIneptique** [perseids-project/perseids_docs#403]
Right now, it seems that we are limited through hardcoded dictionaries.

It would be great if by going to our user settings, we could provide additional ontologies. This would be of great use for students MA Thesis or related objective no ?
On top of that, I do not think implementation would be a lot of pain (while not being pain free)

**Comment by balmas** [comment]
@PonteIneptique you mean this for Plokamos correct?

**Comment by balmas** [comment]
closing and entering in plokamos issues.
