### ISSUE TITLE
Error on Finalization

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#406]
@balmas cc: @wsalesky Not sure if this is a Perseids or Syriaca issue: 

When I submit the finalization form for http://sosol.perseids.org/sosol/publications/35792 on the NHSL Final Approval board, I get the following error: 

> Error preprocessing finalization copy. Received error response 401 Unauthorized POSTING to /exist/apps/srophe-admin/modules/services/sosol-pp.xql

**Comment by balmas** [comment]
hmm. yes this is from the srophe preprocessing service. @wsalesky has the key changed? I'm posting to http://wwwb.library.vanderbilt.edu/exist/apps/srophe-admin/modules/services/sosol-pp.xql with the key you gave me previously.

**Comment by nathangibson** [comment]
By the way, up to this point I was able to take a record through all 3 NHSL review boards.

**Comment by wsalesky** [comment]
@nathangibson can you try it now?

**Comment by nathangibson** [comment]
Yay, it worked! https://github.com/srophe/srophe-app-data/pull/716 

Thank you both! 

BTW, we won't merge the pull request as this was just a test. FWIW, "perseids-proxy-user" received a "First-time contributor" badge from Github :-)

**Comment by wsalesky** [comment]
@balmas Bad permissions on the file caused the issue. The key is fine.

**Comment by balmas** [comment]
@wsalesky  thanks for the quick fix!
