### ISSUE TITLE
Voting workflow

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#408]
@balmas I'm thinking about how reviewers would experience the workflow and would like to suggest some interface tweaks. (This issue and the next 2.) Note: The editors have not had a chance to discuss these fully, so whatever solutions you implement are ones we'll need to test and discuss further. 

First, regarding voting: I think if you're assigned a record to vote on it's not obvious what to do once you click on it. It takes you to "Overview" and there's no visible Vote button, so you have to know to click on "Preview" or "XML" to find the Vote button. 

What would you think about going directly to "Preview" when the link is clicked? Or else somehow labeling the voting more clearly?

**Comment by balmas** [comment]
going to preview is very easy - it's actually what happens if you click the "Document" option under Display Titles (right action bar). I had set the default for the boards view to Publication, but it's one line change to make that default Document.

**Comment by nathangibson** [comment]
Sounds good, let's do it. Thanks!

**Comment by balmas** [comment]
ok. will get it done this weekend.
