### ISSUE TITLE
Showing comments

### ISSUE THREAD

**Issue by nathangibson** [perseids-project/perseids_docs#409]
@balmas -- This is the 2nd workflow/interface suggestion: 

Previous editors’/reviewers’ are important for the voter/finalizer to see. However, you have to click on the “Comments” button to see them. Would it be possible to display (or at least summarize) these somewhere more obvious, like under “Overview,” “History,” or “Preview"?

**Comment by balmas** [comment]
I could add the last X comments to the Overview screen, near where the last 5 edits in the history displays now.   I don't think we want to show all comments there because it will be too much overhead for documents with many, but we could show say the last 5. Would that work?

**Comment by nathangibson** [comment]
Showing the last 5 should be sufficient. But per #408 will the user see them if the comments are on "Overview" but the document link goes directly to "Preview"?

**Comment by nathangibson** [comment]
In my view that would be ideal. Thanks!
